"""Ranking model and blueprint generation for niche research."""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import UTC, datetime
import math
import re

from app.services.providers import BookSignal


@dataclass(slots=True)
class KeywordBlueprint:
    """Candidate keyword and scoring inputs generated by the research pipeline."""

    keyword_text: str
    summary: str
    demand_score: float
    trend_score: float
    intent_score: float
    hook_score: float
    monetization_score: float
    competition_score: float
    seasonality_score: float
    cpc_usd: float
    positives: list[str]
    risks: list[str]
    landing_page_angles: list[str]
    evidence_count: int = 0
    provider_coverage: int = 0
    average_rating: float | None = None
    review_count: int | None = None


@dataclass(slots=True)
class PhraseEvidence:
    """Evidence collected for a candidate phrase before blueprint generation."""

    total_count: int = 0
    title_count: int = 0
    category_count: int = 0
    provider_sources: set[str] = field(default_factory=set)


ROMANCE_DISCOVERY_TERMS: tuple[str, ...] = (
    "dark romance",
    "enemies to lovers romance",
    "small town romance",
    "sports romance",
    "clean romance",
    "second chance romance",
    "paranormal romance",
    "romantic suspense",
    "historical romance",
    "billionaire romance",
    "mafia romance",
    "cowboy romance",
    "workplace romance",
    "friends to lovers romance",
    "why choose romance",
    "rom com romance",
)

ROMANCE_FALLBACK_TERMS: tuple[str, ...] = (
    "dark romance",
    "enemies to lovers romance",
    "small town romance",
    "sports romance",
    "clean romance",
    "second chance romance",
)


TROPE_BOOSTS: dict[str, float] = {
    "enemies to lovers": 14.0,
    "dark": 10.0,
    "small town": 8.0,
    "sports": 9.0,
    "clean": 7.0,
    "second chance": 8.0,
    "paranormal": 9.0,
    "suspense": 9.0,
    "historical": 7.0,
    "billionaire": 6.0,
}

_GENERIC_MARKET_TERMS = {
    "best",
    "bestseller",
    "bestsellers",
    "book",
    "books",
    "fiction",
    "greatest",
    "guide",
    "handbook",
    "kindle",
    "manual",
    "novel",
    "novels",
}
_STOPWORDS = {"a", "an", "and", "for", "in", "of", "the", "to", "your"}
_AUDIENCE_TERMS = {
    "adults",
    "beginners",
    "busy professionals",
    "children",
    "creatives",
    "entrepreneurs",
    "men",
    "mothers",
    "parents",
    "professionals",
    "students",
    "teens",
    "women",
}
_PAIN_TERMS = {
    "anxiety",
    "burnout",
    "confidence",
    "depression",
    "esteem",
    "focus",
    "grief",
    "habits",
    "overthinking",
    "procrastination",
    "recovery",
    "sleep",
    "stress",
    "trauma",
}
_PROMISE_TERMS = {
    "build",
    "clarity",
    "discipline",
    "heal",
    "healing",
    "improve",
    "overcome",
    "recovery",
    "reset",
    "transform",
}
_FORMAT_TERMS = {"guide", "handbook", "journal", "manual", "planner", "workbook"}


def build_keyword_blueprints(seed_niche: str, book_signals: list[BookSignal], max_candidates: int) -> list[KeywordBlueprint]:
    """Build ranked keyword blueprints from signals and curated priors."""
    candidate_phrases = _candidate_phrases(seed_niche, book_signals)[: max_candidates * 3]
    blueprints = [_score_phrase(seed_niche, phrase, book_signals) for phrase in candidate_phrases]
    blueprints = _dedupe_blueprints(seed_niche, blueprints)
    blueprints.sort(key=_ranking_value, reverse=True)
    return blueprints[:max_candidates]


def _candidate_phrases(seed_niche: str, book_signals: list[BookSignal]) -> list[str]:
    normalized_seed = seed_niche.strip().lower()
    phrase_evidence = _phrase_evidence_from_signals(normalized_seed, book_signals)
    phrase_counts = {
        phrase: evidence.total_count
        for phrase, evidence in phrase_evidence.items()
        if not _reject_phrase(normalized_seed, phrase, evidence)
    }

    if normalized_seed == "romance":
        for term in ROMANCE_DISCOVERY_TERMS:
            term_tokens = set(_tokens(term))
            matches = 0
            for signal in book_signals:
                haystack_tokens = set(_tokens(" ".join([signal.title, *signal.categories])))
                if term_tokens.intersection(haystack_tokens):
                    matches += 1
            if matches:
                phrase_counts[term] = phrase_counts.get(term, 0) + matches * 2

    if phrase_counts:
        return [phrase for phrase, _ in sorted(phrase_counts.items(), key=lambda item: (-item[1], item[0]))]

    if normalized_seed == "romance":
        return list(ROMANCE_FALLBACK_TERMS)

    return []


def _phrase_evidence_from_signals(normalized_seed: str, book_signals: list[BookSignal]) -> dict[str, PhraseEvidence]:
    phrase_counts: dict[str, PhraseEvidence] = {}
    seed_tokens = set(_tokens(normalized_seed))
    for signal in book_signals:
        signal_fields = [signal.title, *signal.categories]
        has_seed_context = any(_has_seed_context(normalized_seed, seed_tokens, value) for value in signal_fields)
        for index, raw_phrase in enumerate(signal_fields):
            phrase = _normalize_phrase(raw_phrase)
            if not phrase or len(phrase.split()) > 5:
                continue
            phrase_tokens = set(_tokens(phrase))
            if seed_tokens and not seed_tokens.intersection(phrase_tokens) and not (
                has_seed_context and _specificity_strength(phrase) >= 2.0
            ):
                continue
            evidence = phrase_counts.setdefault(phrase, PhraseEvidence())
            evidence.total_count += 1
            if index == 0:
                evidence.title_count += 1
            else:
                evidence.category_count += 1
            evidence.provider_sources.add(signal.source)

    return phrase_counts


def _score_phrase(seed_niche: str, phrase: str, book_signals: list[BookSignal]) -> KeywordBlueprint:
    matched_signals = _matching_signals(phrase, book_signals)
    provider_coverage = len({signal.source for signal in matched_signals})
    evidence_count = len(matched_signals)
    review_count = sum(signal.review_count or 0 for signal in matched_signals)
    ratings = [signal.average_rating for signal in matched_signals if signal.average_rating is not None]
    average_rating = round(sum(ratings) / len(ratings), 2) if ratings else None
    specificity_strength = _specificity_strength(phrase)
    generic_penalty = _generic_phrase_penalty(seed_niche, phrase)

    demand_score = min(100.0, 45.0 + math.log1p(review_count + evidence_count * 120) * 8.5 + provider_coverage * 4.0)
    trend_score = min(100.0, 48.0 + _recency_share(matched_signals) * 28.0 + provider_coverage * 3.0)
    intent_score = min(100.0, 58.0 + _intent_score(phrase) + specificity_strength * 4.0 - generic_penalty * 0.3)
    hook_score = min(100.0, 55.0 + _hook_score(phrase) + specificity_strength * 3.0 - generic_penalty * 0.2)
    monetization_score = min(100.0, 52.0 + _monetization_score(phrase, average_rating, review_count))
    competition_score = min(
        100.0,
        18.0 + math.log1p(review_count + evidence_count * 50) * 8.0 + _broadness_penalty(phrase) + generic_penalty * 0.5,
    )
    seasonality_score = min(100.0, 35.0 + _seasonality_score(phrase))
    cpc_usd = round(0.85 + monetization_score / 80.0 + intent_score / 140.0, 2)

    summary = _summary_for_phrase(seed_niche, phrase, demand_score, trend_score, competition_score)
    positives = _positives_for_phrase(phrase, provider_coverage, evidence_count)
    risks = _risks_for_phrase(phrase, competition_score, provider_coverage)
    landing_page_angles = _angles_for_phrase(phrase)

    return KeywordBlueprint(
        keyword_text=phrase,
        summary=summary,
        demand_score=round(demand_score, 1),
        trend_score=round(trend_score, 1),
        intent_score=round(intent_score, 1),
        hook_score=round(hook_score, 1),
        monetization_score=round(monetization_score, 1),
        competition_score=round(competition_score, 1),
        seasonality_score=round(seasonality_score, 1),
        cpc_usd=cpc_usd,
        positives=positives,
        risks=risks,
        landing_page_angles=landing_page_angles,
        evidence_count=evidence_count,
        provider_coverage=provider_coverage,
        average_rating=average_rating,
        review_count=review_count,
    )


def _matching_signals(phrase: str, book_signals: list[BookSignal]) -> list[BookSignal]:
    phrase_tokens = set(_tokens(phrase))
    if not phrase_tokens:
        return []
    matches: list[BookSignal] = []
    for signal in book_signals:
        haystack_tokens = set(_tokens(" ".join([signal.title, *signal.categories])))
        overlap = phrase_tokens.intersection(haystack_tokens)
        if phrase_tokens.issubset(haystack_tokens) or len(overlap) >= max(1, min(2, len(phrase_tokens) - 1)):
            matches.append(signal)
    return matches


def _recency_share(signals: list[BookSignal]) -> float:
    years = [signal.published_year for signal in signals if signal.published_year is not None]
    if not years:
        return 0.0
    current_year = datetime.now(UTC).year
    recent = sum(1 for year in years if year >= current_year - 5)
    return recent / len(years)


def _intent_score(phrase: str) -> float:
    bonuses = {
        "for beginners": 10.0,
        "guide": 8.0,
        "workbook": 9.0,
        "journal": 7.0,
    }
    score = 12.0
    for key, value in bonuses.items():
        if key in phrase:
            score += value
    if "romance" in phrase:
        score += 14.0
    return score


def _hook_score(phrase: str) -> float:
    score = 10.0
    for trope, boost in TROPE_BOOSTS.items():
        if trope in phrase:
            score += boost
    score += min(12.0, len(_tokens(phrase)) * 2.0)
    return score


def _monetization_score(phrase: str, average_rating: float | None, review_count: int) -> float:
    score = 10.0
    if average_rating is not None:
        score += max(0.0, average_rating - 3.5) * 10.0
    score += min(18.0, math.log1p(review_count) * 2.6)
    if any(keyword in phrase for keyword in ("romance", "suspense", "paranormal", "sports")):
        score += 12.0
    return score


def _broadness_penalty(phrase: str) -> float:
    token_count = len(_tokens(phrase))
    if token_count <= 2:
        return 16.0
    if token_count == 3:
        return 10.0
    return 6.0


def _seasonality_score(phrase: str) -> float:
    if "sports" in phrase:
        return 16.0
    if "historical" in phrase:
        return 8.0
    if "paranormal" in phrase:
        return 14.0
    return 11.0


def _summary_for_phrase(seed_niche: str, phrase: str, demand_score: float, trend_score: float, competition_score: float) -> str:
    profile = _specificity_profile(phrase)
    specificity_notes: list[str] = []
    if profile["audience"]:
        specificity_notes.append(f"audience {', '.join(profile['audience'])}")
    if profile["pain"]:
        specificity_notes.append(f"problem focus {', '.join(profile['pain'])}")
    if profile["promise"]:
        specificity_notes.append(f"outcome {', '.join(profile['promise'])}")
    specificity_tail = ""
    if specificity_notes:
        specificity_tail = f" It signals {'; '.join(specificity_notes[:2])}."
    return (
        f"{phrase.title()} shows ebook potential inside {seed_niche} with "
        f"demand {round(demand_score, 1)}, trend {round(trend_score, 1)}, and "
        f"competition {round(competition_score, 1)}.{specificity_tail}"
    )


def _positives_for_phrase(phrase: str, provider_coverage: int, evidence_count: int) -> list[str]:
    profile = _specificity_profile(phrase)
    positives = [
        f"Specific positioning around {phrase}.",
        f"Backed by {max(1, provider_coverage)} provider sources and {max(1, evidence_count)} matching market signals.",
    ]
    if profile["audience"]:
        positives.append(f"Audience signal is explicit through {', '.join(profile['audience'])}.")
    if profile["pain"]:
        positives.append(f"Problem-led positioning is clearer through {', '.join(profile['pain'])}.")
    if "romance" in phrase:
        positives.append("Reader intent is explicit and easy to message in ebook packaging.")
    return positives


def _risks_for_phrase(phrase: str, competition_score: float, provider_coverage: int) -> list[str]:
    risks = []
    if _specificity_strength(phrase) < 2.0:
        risks.append("Specific audience, pain, or promise signals are weak, so niche fit may still be broad.")
    if competition_score >= 65:
        risks.append("Competition is high, so differentiation in title, angle, or audience is necessary.")
    if provider_coverage <= 1:
        risks.append("Signal coverage is thin, so validate with additional marketplace evidence before scaling.")
    if not risks:
        risks.append("Still needs cover, blurb, and audience-angle validation before launch.")
    return risks


def _angles_for_phrase(phrase: str) -> list[str]:
    profile = _specificity_profile(phrase)
    if profile["audience"]:
        audience = profile["audience"][0]
        return [
            f"A focused ebook for {audience} built around {phrase}.",
            f"A promise-led landing page that shows why {phrase} matters specifically for {audience}.",
        ]
    if profile["pain"]:
        pain = profile["pain"][0]
        return [
            f"A pain-to-outcome ebook positioned around {pain} inside {phrase}.",
            f"A validation page that tests whether readers buy {phrase} as a solution to {pain}.",
        ]
    return [
        f"A focused ebook built around {phrase}.",
        f"A landing page that tests whether {phrase} is specific enough to convert as a niche offer.",
    ]


def _normalize_phrase(value: str) -> str:
    value = re.sub(r"[^a-z0-9\\s]", " ", value.lower())
    value = re.sub(r"\\s+", " ", value).strip()
    return value


def _tokens(value: str) -> list[str]:
    return [token for token in _normalize_phrase(value).split() if token]


def _has_seed_context(normalized_seed: str, seed_tokens: set[str], value: str) -> bool:
    phrase = _normalize_phrase(value)
    if not phrase:
        return False
    phrase_tokens = set(_tokens(phrase))
    if phrase == normalized_seed:
        return True
    return bool(seed_tokens and seed_tokens.issubset(phrase_tokens))


def _specificity_profile(phrase: str) -> dict[str, list[str]]:
    normalized_phrase = _normalize_phrase(phrase)
    phrase_tokens = set(_tokens(normalized_phrase))
    profile = {
        "audience": [],
        "pain": [],
        "promise": [],
        "format": [],
    }
    for term in sorted(_AUDIENCE_TERMS):
        if _term_matches_phrase(term, normalized_phrase, phrase_tokens):
            profile["audience"].append(term)
    for term in sorted(_PAIN_TERMS):
        if _term_matches_phrase(term, normalized_phrase, phrase_tokens):
            profile["pain"].append(term)
    for term in sorted(_PROMISE_TERMS):
        if _term_matches_phrase(term, normalized_phrase, phrase_tokens):
            profile["promise"].append(term)
    for term in sorted(_FORMAT_TERMS):
        if _term_matches_phrase(term, normalized_phrase, phrase_tokens):
            profile["format"].append(term)
    return profile


def _term_matches_phrase(term: str, normalized_phrase: str, phrase_tokens: set[str]) -> bool:
    term_tokens = _tokens(term)
    if len(term_tokens) == 1:
        return term_tokens[0] in phrase_tokens
    return term in normalized_phrase


def _specificity_strength(phrase: str) -> float:
    profile = _specificity_profile(phrase)
    return (
        len(profile["audience"]) * 1.5
        + len(profile["pain"]) * 1.2
        + len(profile["promise"]) * 1.0
        + len(profile["format"]) * 0.6
    )


def _generic_phrase_penalty(seed_niche: str, phrase: str) -> float:
    normalized_seed = _normalize_phrase(seed_niche)
    phrase_tokens = _tokens(phrase)
    seed_tokens = set(_tokens(normalized_seed))
    remaining_tokens = [
        token for token in phrase_tokens if token not in seed_tokens and token not in _STOPWORDS
    ]
    if not remaining_tokens:
        return 28.0
    if all(token in _GENERIC_MARKET_TERMS for token in remaining_tokens):
        return 24.0
    return 0.0


def _reject_phrase(normalized_seed: str, phrase: str, evidence: PhraseEvidence) -> bool:
    if _is_audience_only_fragment(phrase):
        return True
    if _is_exact_query_echo(normalized_seed, phrase):
        return True
    if _generic_phrase_penalty(normalized_seed, phrase) >= 20.0:
        return True
    if _is_title_artifact(phrase, evidence):
        return True
    if evidence.category_count == 0 and evidence.total_count <= 1 and len(evidence.provider_sources) <= 1:
        if _specificity_strength(phrase) < 2.0:
            return True
    return False


def _blueprint_dedupe_key(seed_niche: str, phrase: str) -> str:
    seed_tokens = set(_tokens(seed_niche))
    filtered_tokens = [
        token
        for token in _tokens(phrase)
        if token not in seed_tokens and token not in _STOPWORDS and token not in _GENERIC_MARKET_TERMS
    ]
    if not filtered_tokens:
        filtered_tokens = [token for token in _tokens(phrase) if token not in _STOPWORDS]
    return " ".join(filtered_tokens)


def _is_exact_query_echo(seed_niche: str, phrase: str) -> bool:
    return _blueprint_dedupe_key(seed_niche, phrase) == ""


def _is_title_artifact(phrase: str, evidence: PhraseEvidence) -> bool:
    if evidence.title_count == 0:
        return False
    if evidence.category_count > 0:
        return False
    return _specificity_strength(phrase) < 2.0


def _is_audience_only_fragment(phrase: str) -> bool:
    profile = _specificity_profile(phrase)
    return bool(profile["audience"]) and not profile["pain"] and not profile["promise"]


def _dedupe_blueprints(seed_niche: str, blueprints: list[KeywordBlueprint]) -> list[KeywordBlueprint]:
    deduped: dict[str, KeywordBlueprint] = {}
    for blueprint in sorted(blueprints, key=_ranking_value, reverse=True):
        key = _blueprint_dedupe_key(seed_niche, blueprint.keyword_text)
        existing = deduped.get(key)
        if existing is None or _ranking_value(blueprint) > _ranking_value(existing):
            deduped[key] = blueprint
    return list(deduped.values())


def _ranking_value(item: KeywordBlueprint) -> float:
    specificity_strength = _specificity_strength(item.keyword_text)
    specificity_bonus = min(10.0, specificity_strength * 3.0)
    base_score = round(
        item.demand_score * 0.24
        + item.trend_score * 0.14
        + item.intent_score * 0.16
        + item.hook_score * 0.17
        + item.monetization_score * 0.15
        + (100.0 - item.competition_score) * 0.10
        + min(10.0, item.provider_coverage * 2.0)
        + min(8.0, math.log1p(item.evidence_count) * 2.0),
        2,
    )
    return round(base_score + specificity_bonus, 2)
