"""Ranking model and blueprint generation for niche research."""

from __future__ import annotations

from dataclasses import dataclass
from datetime import UTC, datetime
import math
import re

from app.services.providers import BookSignal


@dataclass(slots=True)
class KeywordBlueprint:
    """Candidate keyword and scoring inputs generated by the research pipeline."""

    keyword_text: str
    summary: str
    demand_score: float
    trend_score: float
    intent_score: float
    hook_score: float
    monetization_score: float
    competition_score: float
    seasonality_score: float
    cpc_usd: float
    positives: list[str]
    risks: list[str]
    landing_page_angles: list[str]
    evidence_count: int = 0
    provider_coverage: int = 0
    average_rating: float | None = None
    review_count: int | None = None


ROMANCE_DISCOVERY_TERMS: tuple[str, ...] = (
    "dark romance",
    "enemies to lovers romance",
    "small town romance",
    "sports romance",
    "clean romance",
    "second chance romance",
    "paranormal romance",
    "romantic suspense",
    "historical romance",
    "billionaire romance",
    "mafia romance",
    "cowboy romance",
    "workplace romance",
    "friends to lovers romance",
    "why choose romance",
    "rom com romance",
)

ROMANCE_FALLBACK_TERMS: tuple[str, ...] = (
    "dark romance",
    "enemies to lovers romance",
    "small town romance",
    "sports romance",
    "clean romance",
    "second chance romance",
)


TROPE_BOOSTS: dict[str, float] = {
    "enemies to lovers": 14.0,
    "dark": 10.0,
    "small town": 8.0,
    "sports": 9.0,
    "clean": 7.0,
    "second chance": 8.0,
    "paranormal": 9.0,
    "suspense": 9.0,
    "historical": 7.0,
    "billionaire": 6.0,
}


def build_keyword_blueprints(seed_niche: str, book_signals: list[BookSignal], max_candidates: int) -> list[KeywordBlueprint]:
    """Build ranked keyword blueprints from signals and curated priors."""
    candidate_phrases = _candidate_phrases(seed_niche, book_signals)[:max_candidates]
    blueprints = [_score_phrase(seed_niche, phrase, book_signals) for phrase in candidate_phrases]
    blueprints.sort(key=_ranking_value, reverse=True)
    return blueprints[:max_candidates]


def _candidate_phrases(seed_niche: str, book_signals: list[BookSignal]) -> list[str]:
    normalized_seed = seed_niche.strip().lower()
    phrase_counts: dict[str, int] = _phrase_counts_from_signals(normalized_seed, book_signals)

    if normalized_seed == "romance":
        for term in ROMANCE_DISCOVERY_TERMS:
            term_tokens = set(_tokens(term))
            matches = 0
            for signal in book_signals:
                haystack_tokens = set(_tokens(" ".join([signal.title, *signal.categories])))
                if term_tokens.intersection(haystack_tokens):
                    matches += 1
            if matches:
                phrase_counts[term] = phrase_counts.get(term, 0) + matches * 2

    if phrase_counts:
        return [phrase for phrase, _ in sorted(phrase_counts.items(), key=lambda item: (-item[1], item[0]))]

    if normalized_seed == "romance":
        return list(ROMANCE_FALLBACK_TERMS)

    return [
        normalized_seed,
        f"{normalized_seed} for beginners",
        f"{normalized_seed} workbook",
        f"{normalized_seed} guide",
        f"{normalized_seed} journal",
    ]


def _phrase_counts_from_signals(normalized_seed: str, book_signals: list[BookSignal]) -> dict[str, int]:
    phrase_counts: dict[str, int] = {}
    seed_tokens = set(_tokens(normalized_seed))
    for signal in book_signals:
        for raw_phrase in [signal.title, *signal.categories]:
            phrase = _normalize_phrase(raw_phrase)
            if not phrase or len(phrase.split()) > 5:
                continue
            phrase_tokens = set(_tokens(phrase))
            if seed_tokens and not seed_tokens.intersection(phrase_tokens):
                continue
            phrase_counts[phrase] = phrase_counts.get(phrase, 0) + 1

    return phrase_counts


def _score_phrase(seed_niche: str, phrase: str, book_signals: list[BookSignal]) -> KeywordBlueprint:
    matched_signals = _matching_signals(phrase, book_signals)
    provider_coverage = len({signal.source for signal in matched_signals})
    evidence_count = len(matched_signals)
    review_count = sum(signal.review_count or 0 for signal in matched_signals)
    ratings = [signal.average_rating for signal in matched_signals if signal.average_rating is not None]
    average_rating = round(sum(ratings) / len(ratings), 2) if ratings else None

    demand_score = min(100.0, 45.0 + math.log1p(review_count + evidence_count * 120) * 8.5 + provider_coverage * 4.0)
    trend_score = min(100.0, 48.0 + _recency_share(matched_signals) * 28.0 + provider_coverage * 3.0)
    intent_score = min(100.0, 58.0 + _intent_score(phrase))
    hook_score = min(100.0, 55.0 + _hook_score(phrase))
    monetization_score = min(100.0, 52.0 + _monetization_score(phrase, average_rating, review_count))
    competition_score = min(100.0, 18.0 + math.log1p(review_count + evidence_count * 50) * 8.0 + _broadness_penalty(phrase))
    seasonality_score = min(100.0, 35.0 + _seasonality_score(phrase))
    cpc_usd = round(0.85 + monetization_score / 80.0 + intent_score / 140.0, 2)

    summary = _summary_for_phrase(seed_niche, phrase, demand_score, trend_score, competition_score)
    positives = _positives_for_phrase(phrase, provider_coverage, evidence_count)
    risks = _risks_for_phrase(phrase, competition_score, provider_coverage)
    landing_page_angles = _angles_for_phrase(phrase)

    return KeywordBlueprint(
        keyword_text=phrase,
        summary=summary,
        demand_score=round(demand_score, 1),
        trend_score=round(trend_score, 1),
        intent_score=round(intent_score, 1),
        hook_score=round(hook_score, 1),
        monetization_score=round(monetization_score, 1),
        competition_score=round(competition_score, 1),
        seasonality_score=round(seasonality_score, 1),
        cpc_usd=cpc_usd,
        positives=positives,
        risks=risks,
        landing_page_angles=landing_page_angles,
        evidence_count=evidence_count,
        provider_coverage=provider_coverage,
        average_rating=average_rating,
        review_count=review_count,
    )


def _matching_signals(phrase: str, book_signals: list[BookSignal]) -> list[BookSignal]:
    phrase_tokens = set(_tokens(phrase))
    if not phrase_tokens:
        return []
    matches: list[BookSignal] = []
    for signal in book_signals:
        haystack_tokens = set(_tokens(" ".join([signal.title, *signal.categories])))
        overlap = phrase_tokens.intersection(haystack_tokens)
        if phrase_tokens.issubset(haystack_tokens) or len(overlap) >= max(1, min(2, len(phrase_tokens) - 1)):
            matches.append(signal)
    return matches


def _recency_share(signals: list[BookSignal]) -> float:
    years = [signal.published_year for signal in signals if signal.published_year is not None]
    if not years:
        return 0.0
    current_year = datetime.now(UTC).year
    recent = sum(1 for year in years if year >= current_year - 5)
    return recent / len(years)


def _intent_score(phrase: str) -> float:
    bonuses = {
        "for beginners": 10.0,
        "guide": 8.0,
        "workbook": 9.0,
        "journal": 7.0,
    }
    score = 12.0
    for key, value in bonuses.items():
        if key in phrase:
            score += value
    if "romance" in phrase:
        score += 14.0
    return score


def _hook_score(phrase: str) -> float:
    score = 10.0
    for trope, boost in TROPE_BOOSTS.items():
        if trope in phrase:
            score += boost
    score += min(12.0, len(_tokens(phrase)) * 2.0)
    return score


def _monetization_score(phrase: str, average_rating: float | None, review_count: int) -> float:
    score = 10.0
    if average_rating is not None:
        score += max(0.0, average_rating - 3.5) * 10.0
    score += min(18.0, math.log1p(review_count) * 2.6)
    if any(keyword in phrase for keyword in ("romance", "suspense", "paranormal", "sports")):
        score += 12.0
    return score


def _broadness_penalty(phrase: str) -> float:
    token_count = len(_tokens(phrase))
    if token_count <= 2:
        return 16.0
    if token_count == 3:
        return 10.0
    return 6.0


def _seasonality_score(phrase: str) -> float:
    if "sports" in phrase:
        return 16.0
    if "historical" in phrase:
        return 8.0
    if "paranormal" in phrase:
        return 14.0
    return 11.0


def _summary_for_phrase(seed_niche: str, phrase: str, demand_score: float, trend_score: float, competition_score: float) -> str:
    return (
        f"{phrase.title()} shows strong ebook potential inside {seed_niche} with "
        f"demand {round(demand_score, 1)}, trend {round(trend_score, 1)}, and "
        f"competition {round(competition_score, 1)}."
    )


def _positives_for_phrase(phrase: str, provider_coverage: int, evidence_count: int) -> list[str]:
    positives = [f"Specific positioning around {phrase}.", f"Backed by {max(1, provider_coverage)} provider sources and {max(1, evidence_count)} matching market signals."]
    if "romance" in phrase:
        positives.append("Reader intent is explicit and easy to message in ebook packaging.")
    return positives


def _risks_for_phrase(phrase: str, competition_score: float, provider_coverage: int) -> list[str]:
    risks = []
    if competition_score >= 65:
        risks.append("Competition is high, so differentiation in title, angle, or audience is necessary.")
    if provider_coverage <= 1:
        risks.append("Signal coverage is thin, so validate with additional marketplace evidence before scaling.")
    if not risks:
        risks.append("Still needs cover, blurb, and audience-angle validation before launch.")
    return risks


def _angles_for_phrase(phrase: str) -> list[str]:
    return [
        f"A fast, trope-first ebook built around {phrase}.",
        f"Audience-specific promise that makes {phrase} feel more targeted and bingeable.",
    ]


def _normalize_phrase(value: str) -> str:
    value = re.sub(r"[^a-z0-9\\s]", " ", value.lower())
    value = re.sub(r"\\s+", " ", value).strip()
    return value


def _tokens(value: str) -> list[str]:
    return [token for token in _normalize_phrase(value).split() if token]


def _ranking_value(item: KeywordBlueprint) -> float:
    return round(
        item.demand_score * 0.24
        + item.trend_score * 0.14
        + item.intent_score * 0.16
        + item.hook_score * 0.17
        + item.monetization_score * 0.15
        + (100.0 - item.competition_score) * 0.10
        + min(10.0, item.provider_coverage * 2.0)
        + min(8.0, math.log1p(item.evidence_count) * 2.0),
        2,
    )
